### ISSUE TITLE
LuaJIT

### ISSUE THREAD

**Issue by abigpotostew** [danomatika/ofxLua#11]
Have you considered using LuaJIT to get better performance?
http://luajit.org

**Comment by danomatika** [comment]
I have SWIG working fully with ofxLua in the `swig` branch now which also uses LuaJIT on embedded Linux (RPI). I also added notes about using it instead of LuaJIT on other platforms which now a lot easier since you only need to remove the Lua sources and link with the LuaJIT download or system package.

**Comment by abigpotostew** [comment]
The Swig approach looks much better!

**Comment by danomatika** [comment]
Thanks. It was a lot of work, but I think it was worth it, plus it works with the ProjectGenerator now. If you have the time, can you check it on RPI?

**Comment by abigpotostew** [comment]
I tried out the swig branch on my pi, but got stuck in compilation due to "cairo-features.h" not being found. I'm not sure if this is an OF issue or from the swig branch. Like I said, I'm a fish out of water when it comes to makefiles and linking issues. But the latest master build seems to be working fine. I'm going to ask on the OF forums about this.
https://gist.github.com/abigpotostew/f893f7fe79881fdfc537
